project_id = "mgxnwtynaaawlfnaxidj"

[functions.criar-usuario-tenant]
verify_jwt = false

[functions.criar-tenant-admin]
verify_jwt = false

[functions.gerenciar-membros-tenant]
verify_jwt = false

[functions.desativar-membro-tenant]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false
